### ISSUE TITLE
Idea: a checkData Function [nut.command.add]

### ISSUE THREAD

**Issue by EmanSza** [Nutscript/NutScript#102]
When adding commands to Nutscript this bit of code runs

```
if (!data.onCheckAccess) then
		-- Check if the command is for basic admins only.
		if (data.adminOnly) then
			data.onCheckAccess = function(client)
				return client:IsAdmin()
			end
		-- Or if it is only for super administrators.
		elseif (data.superAdminOnly) then
			data.onCheckAccess = function(client)
				return client:IsSuperAdmin()
			end
		-- Or if we specify a usergroup allowed to use this.
		elseif (data.group) then
			-- The group property can be a table of usergroups.
			if istable(data.group) then
				data.onCheckAccess = function(client)
					-- Check if the client's group is allowed.
					for _, v in ipairs(data.group) do
						if (client:IsUserGroup(v)) then
							return true
						end
					end

					return false
				end
			-- Otherwise it is most likely a string.
			else
				data.onCheckAccess = function(client)
					return client:IsUserGroup(data.group)
				end
			end
		end
	end
```
	
but this itself creates a lot of issues
	
When you wish to make modifications to how the data itself is checked you have to modify how the function itself works, would be wonderful if I could just override a function instead since it seems to return true or false.
	
I tried doing this but I just straight-up broke Nutscript so I made a issue in hopes someone who is better than me edits the code

**Comment by TovarischPootis** [comment]
This segment of the code acts as a way for you to add custom access checking for clients, such as isAdmin, isSuperAdmin, in case you want to limit commands to flags or factions or classes or whatever. It should only return true or false because code elsewhere uses it to limit or allow access. It shouldn't return anything else. Elaborate what do you want changed?

**Comment by EmanSza** [comment]
Because the segment of code is not a function the only way to change how commands access works is to actually change nutscript itself

This makes nutscript inflexible and difficult to use, how nutscript checks command access should be done by a function.

This allows developers to change how command access works while keeping their code base consistent since they would be able to override the function

**Comment by TovarischPootis** [comment]
I'm confused.

NS checks if there is a onCheckAccess function, such as
`	onCheckAccess = function(client)
		return client:getChar():hasItem("item")
	end
	`
	
if this is not present, it checks if there's an adminOnly, superAdminOnly or group is present and automatically creates an access check function.

I don't understand what your complaint is

**Comment by EmanSza** [comment]
if you're using OnCheckAccess it's a variable of "data" so if I want to completely override it for every command I make I would need to override it again. this is inconsistent and inflexible. It would be better if there was a global function that can simply be overrode instead of overriding it everytime I make a new NS Command

**Comment by zoephix** [comment]
I don't see the problem, it's really not that much effort to override it again for any new commands...
