### ISSUE TITLE
NS config not able to be edited 

### ISSUE THREAD

**Issue by ItzAzapp** [Nutscript/NutScript#106]
I can not edit the config in the F1 Menu. All the options have are grey and do not update when I change them. I tried manually editing the config file and still nothing changed. The functions in the Q menu work. If you need to reach me I will be checking this thread but if its urgent my discord is Itz Azap#7785
![](https://i.gyazo.com/c8550779098f9f42a6e5f5d91778da58.jpg)

![](https://i.gyazo.com/15e5105cf4e10f1510a156a572916538.png)

**Comment by TovarischPootis** [comment]
Looks like an addon conflict rather than an NS issue, seeing how default GMod controls are affected as well.
Otherwise it might be some modification you've done (and have not shown), as this is the first time I see this issue.
