### ISSUE TITLE
icon for player class on scoreboard

### ISSUE THREAD

**Issue by kaputttt** [Nutscript/NutScript#174]
I have been looking all over and essentially im trying to find a way to add an icon between the players name and ping at the end. This icon would essentially display what RP class they are... such as a Medic, Radio operator, squad leader etc. Is there anyway to implement this??

**Comment by TovarischPootis** [comment]
You'll have to modify the classes to have the icon assigned, and modify the scoreboard plugin to display the relevant icon. For proper support visit the discord
